INSERT INTO CATEGORY(CATEGORY_ID, NAME) VALUES (1, 'Style & Fashion');
INSERT INTO CATEGORY(CATEGORY_ID, NAME) VALUES (2, 'Electronics');
INSERT INTO CATEGORY(CATEGORY_ID, NAME) VALUES (3, 'Health & Fitness');